{% set version = load_setup_py_data().get('version') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
    name: asvdb
    version: {{ version }}

source:
    #git_url: https://github.com/rapidsai/asvdb.git
    path: ..

build:
    number: {{ git_revision_count }}
    script: python setup.py install
    noarch: python

requirements:
    build:
        - python
        - setuptools
        - boto3
        - botocore

    run:
        - python
        - boto3
        - botocore
test:
    imports:
        - asvdb

about:
    home: https://github.com/rapidsai/asvdb
    license: Apache 2.0
