package:
    name: asvdb
    version: 0.3.3

source:
    #git_url: https://github.com/rapidsai/asvdb.git
    path: ..

build:
    number: 0

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - asvdb

about:
    home: https://github.com/rapidsai/asvdb
    license: Apache 2.0
