{% set version = load_setup_py_data().get('version') %}

package:
    name: asvdb
    version: {{ version }}

source:
    #git_url: https://github.com/rapidsai/asvdb.git
    path: ..

build:
    script: python setup.py install

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - asvdb

about:
    home: https://github.com/rapidsai/asvdb
    license: Apache 2.0
